### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fakerybakery** [afriedman412/sayswho#2]
Hi,
I am getting the error:

```
catalogue.RegistryError: [E892] Unknown function registry: 'vectors'.
```

in `sayswho/__init__.py` line 35.

**Comment by fakerybakery** [comment]
Hi,
Sorry about this, seems to be an issue with my SpaCy installation.

**Comment by afriedman412** [comment]
hey -- did the install instructions work?

(SpaCy can be tricky wrt co-dependencies and I haven't checked for updates in a minute.)

**Comment by fakerybakery** [comment]
Sorry, it was on my end - forgot to create a new venv and I think dependencies from other projects interfered.
